package changelog

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/rs/zerolog/log"
	slackapi "github.com/slack-go/slack"

	"github.com/pixxle/solomon/internal/claude"
	"github.com/pixxle/solomon/internal/config"
	"github.com/pixxle/solomon/internal/git"
	ghclient "github.com/pixxle/solomon/internal/github"
)

// buildTemplateData builds the data map passed to prompt templates.
// The timestamp is passed in so all consumers share the same date.
func buildTemplateData(cl *Changelog, now time.Time) map[string]interface{} {
	return map[string]interface{}{
		"RepoName":   cl.RepoName,
		"Date":       now.Format("2006-01-02"),
		"IsFirstRun": cl.IsFirstRun,
		"Commits":    cl.Commits,
	}
}

func outputSlack(ctx context.Context, cl *Changelog, client *slackapi.Client, channelID, repoPath, model string, tmplData map[string]interface{}) error {
	prompt, err := claude.RenderPrompt("changelog_slack.md.tmpl", tmplData)
	if err != nil {
		return fmt.Errorf("rendering slack prompt: %w", err)
	}

	result, err := claude.RunClaudeText(ctx, prompt, repoPath, model)
	if err != nil {
		return fmt.Errorf("generating slack changelog: %w", err)
	}

	msg := strings.TrimSpace(result.Output)
	if msg == "" {
		return fmt.Errorf("LLM returned empty changelog")
	}

	_, _, err = client.PostMessageContext(ctx, channelID,
		slackapi.MsgOptionText(msg, false),
	)
	return err
}

func outputPR(ctx context.Context, cl *Changelog, repoPath string, ghClient *ghclient.Client, cfg *config.Config, changelogPath, model string, tmplData map[string]interface{}, now time.Time) error {
	prompt, err := claude.RenderPrompt("changelog_pr.md.tmpl", tmplData)
	if err != nil {
		return fmt.Errorf("rendering pr prompt: %w", err)
	}

	result, err := claude.RunClaudeText(ctx, prompt, repoPath, model)
	if err != nil {
		return fmt.Errorf("generating pr changelog: %w", err)
	}

	section := strings.TrimSpace(result.Output)
	if section == "" {
		return fmt.Errorf("LLM returned empty changelog")
	}

	branch := fmt.Sprintf("changelog/update-%s", now.Format("2006-01-02-150405"))

	worktreeBase := filepath.Join(cfg.DataPath, "changelog-worktrees")
	wtDir, err := git.EnsureWorktreeWithIdentity(ctx, branch, repoPath, worktreeBase, cfg.GitUserName, cfg.GitUserEmail)
	if err != nil {
		return fmt.Errorf("creating worktree: %w", err)
	}
	defer git.CleanupWorktree(ctx, branch, repoPath, worktreeBase)

	// Read existing changelog if present
	changelogFullPath := filepath.Join(wtDir, changelogPath)
	existing, _ := os.ReadFile(changelogFullPath)

	// Ensure parent directory exists
	if dir := filepath.Dir(changelogFullPath); dir != "." {
		os.MkdirAll(dir, 0o755)
	}

	// Prepend new section (or create with header)
	var content string
	if len(existing) > 0 {
		content = section + "\n\n" + string(existing)
	} else {
		content = "# Changelog\n\n" + section + "\n"
	}

	if err := os.WriteFile(changelogFullPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing changelog: %w", err)
	}

	// Stage, commit, push
	if err := git.Run(ctx, wtDir, "git", "add", changelogPath); err != nil {
		return fmt.Errorf("staging changelog: %w", err)
	}

	commitMsg := fmt.Sprintf("chore: update changelog for %s", now.Format("2006-01-02"))
	if err := git.Run(ctx, wtDir, "git", "commit", "-m", commitMsg); err != nil {
		return fmt.Errorf("committing changelog: %w", err)
	}

	if err := ghClient.PushBranch(ctx, branch, wtDir); err != nil {
		return fmt.Errorf("pushing branch: %w", err)
	}

	// Check for existing PR
	existingPR, err := ghClient.FindOpenPRForBranch(ctx, branch)
	if err != nil {
		log.Warn().Err(err).Msg("changelog: failed to check for existing PR")
	}
	if existingPR > 0 {
		log.Info().Int("pr", existingPR).Msg("changelog: PR already exists")
		return nil
	}

	// Create PR
	title := fmt.Sprintf("chore: changelog update %s", now.Format("2006-01-02"))
	body := fmt.Sprintf("Automated changelog update for **%s** with %d new commit(s).\n\nGenerated by Solomon changelog plugin.",
		cl.RepoName, len(cl.Commits))

	prNum, err := ghClient.CreatePR(ctx, title, body, branch, false)
	if err != nil {
		return fmt.Errorf("creating PR: %w", err)
	}

	log.Info().Int("pr", prNum).Str("repo", cl.RepoName).Msg("changelog: PR created")
	return nil
}
